server:
  port: 9000

spring:
  datasource:
    username: jalrg_cibertec
    url: jdbc:mysql://proydsw2.cqgcktgw7rag.us-east-1.rds.amazonaws.com:3306/dsw219
    password: Cibertec2019
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop